// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ablrtepdqmubdqaftsxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFibHJ0ZXBkcW11YmRxYWZ0c3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTg3MTIsImV4cCI6MjA1OTQ5NDcxMn0.DYQ4feXIVMiYuorW-DwOfY_r98YltYBS7VO94cxjdwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);